TestNuscenes: false # true or false
# TestNuscenes: true # true or false

ModelConfig: /home/uisee/dl_model_infer/application/bevdet4d_app/cfgs/bevdet_lt_depth.yaml

N: 6
H: 900
W: 1600
cams: [CAM_FRONT_LEFT, CAM_FRONT, CAM_FRONT_RIGHT, CAM_BACK_LEFT, CAM_BACK, CAM_BACK_RIGHT]
sample:
    CAM_FRONT_LEFT: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/imgs/CAM_FRONT_LEFT.jpg
    CAM_FRONT: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/imgs/CAM_FRONT.jpg
    CAM_FRONT_RIGHT: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/imgs/CAM_FRONT_RIGHT.jpg
    CAM_BACK_LEFT: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/imgs/CAM_BACK_LEFT.jpg
    CAM_BACK: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/imgs/CAM_BACK.jpg
    CAM_BACK_RIGHT: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/imgs/CAM_BACK_RIGHT.jpg

CamConfig: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/sample0000.yaml
InputFile: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/0.bin
OutputLidarBox: /home/uisee/dl_model_infer/application/bevdet4d_app/sample0/sample0_lidarbox.txt

ImgStageEngine: /home/uisee/dl_model_infer/workspaces/img_stage_lt_d_fp16.engine
BEVStageEngine: /home/uisee/dl_model_infer/workspaces/bev_stage_lt_d_fp16.engine

OutputDir: /home/uisee/dl_model_infer/workspaces/bevdet_output/

LoadDim: 5
UseDim: 4

dataset_info: /home/uisee/dl_model_infer/application/bevdet4d_app/data/nuscenes/data_infos
